{"name": "test_login_success_user[test_info0]", "status": "broken", "statusDetails": {"message": "TypeError: find_element() argument after * must be an iterable, not NoneType", "trace": "self = <test_cases.test_001_login.TestLogin object at 0x000002368714A6C8>\ntest_info = {'expected': '县域人财物一体化管理系统', 'pwd': '123456', 'user': 'ceshi01'}\nget_browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"bb74ff115f8f7e367c7fdf2c8fa79728\")>\n\n    @pytest.mark.parametrize('test_info', login_data_success)\n    @allure.story(\"登录成功\")\n    def test_login_success_user(self, test_info, get_browser):\n        print(\"------执行登录成功测试用例------\")\n        driver=get_browser\n        expected = test_info['expected']\n>       LoginPage(driver).login(test_info[\"user\"], test_info[\"pwd\"])\n\ntest_001_login.py:75: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pages\\login_page.py:42: in login\n    self.move_click(btn_elem)\n..\\common\\base_page.py:161: in move_click\n    ele= self.wait_clickable_element(locator)\n..\\common\\base_page.py:82: in wait_clickable_element\n    EC.element_to_be_clickable(locator)\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:71: in until\n    value = method(self._driver)\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:297: in __call__\n    element = visibility_of_element_located(self.locator)(driver)\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:128: in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"bb74ff115f8f7e367c7fdf2c8fa79728\")>\nby = None\n\n    def _find_element(driver, by):\n        \"\"\"Looks up an element. Logs and re-raises ``WebDriverException``\n        if thrown.\"\"\"\n        try:\n>           return driver.find_element(*by)\nE           TypeError: find_element() argument after * must be an iterable, not NoneType\n\nC:\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:411: TypeError"}, "attachments": [{"name": "log", "source": "eb45ec01-6cf5-4781-9133-f7deba9b37f9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_info", "value": "{'user': 'ceshi01', 'pwd': '123456', 'expected': '县域人财物一体化管理系统'}"}], "start": 1600343722073, "stop": 1600343731954, "uuid": "10927098-6fbc-4544-b617-249d9ab7323d", "historyId": "90a883f6cc42b550951bb1d2065b328a", "testCaseId": "6c3d92ab5304f589ec15e8c5182b83f4", "fullName": "test_cases.test_001_login.TestLogin#test_login_success_user", "labels": [{"name": "story", "value": "登录成功"}, {"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_001_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-G986QGRS"}, {"name": "thread", "value": "22432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_001_login"}]}